### ISSUE TITLE
Sequence longer than PWM bug.

### ISSUE THREAD

**Issue by j-andrews7** [j-andrews7/VENUSAR#22]
In `motifs.py`, `score_motif` function sometimes throws an error. Basically, put in a noisy bypass for now, but I'm sure it's skipping motifs in the database because of it. Not sure what the issue is, need to debug.

**Comment by j-andrews7** [comment]
I think this might be an issue with chromosome order or something, because if you only use the first ~1000 lines of a file (all one chromosome), it seems to work fine.

**Comment by Crumbs350** [comment]
see issue #35. I think they are potentially related.

**Comment by j-andrews7** [comment]
Pretty sure this has been fixed. See issue #35.
