### ISSUE TITLE
get_motifs length all not individual TF

### ISSUE THREAD

**Issue by Crumbs350** [j-andrews7/VENUSAR#35]
get_motifs max_length is used to track length off all TF Loaded from motif file, thus wing length for variant is too large for most TF and they are ignored. get_motifs should also set/return valid flag by checking that all ACGT have same length matrix.

**Comment by Crumbs350** [comment]
related to issue #22?

**Comment by j-andrews7** [comment]
Quite possible. Testing on the full VCF file will likely tell if so.

**Comment by Crumbs350** [comment]
Fixed awhile ago during implementation of motif.py::MotifElement class calls to sequence.py::SequenceElement class object. Specifically MotifElement.checkValid() determines if motif TF matrix is consistent during addition to the set. MotifArray.motif_scores() makes sure the sequence is reduced to roughly 2x individual motif length based on use of sequence.py::crop_from_left and sequence.py::crop_from_right for trim_amount = wing_l - motif_element.positions + 1
